namespace ERP.Application.DTOs;

public class PutawayTaskListDto { public int Id { get; set; } public int ReceiptId { get; set; } public string ReceiptCode { get; set; } = ""; public int WarehouseId { get; set; } public string WarehouseName { get; set; } = ""; public string Status { get; set; } = ""; public int? AssignedUserId { get; set; } public decimal RequiredBaseQuantity { get; set; } public decimal MovedBaseQuantity { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class PutawayTaskDto : PutawayTaskListDto { [System.Text.Json.Serialization.JsonIgnore(Condition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)] public string? RowVersion { get; set; } public string? ExceptionReason { get; set; } public IReadOnlyList<PutawayTaskItemDto> Items { get; set; } = []; public IReadOnlyList<PutawayMovementDto> Movements { get; set; } = []; }
public sealed class PutawayTaskItemDto { public int Id { get; set; } public int ReceiptLineId { get; set; } public int ProductId { get; set; } public string ProductCode { get; set; } = ""; public string ProductName { get; set; } = ""; public string InventoryStatus { get; set; } = ""; public int SourceLocationId { get; set; } public string SourceLocationCode { get; set; } = ""; public string OperationUnitCode { get; set; } = ""; public string BaseUnitCode { get; set; } = ""; public decimal RequiredOperationQuantity { get; set; } public decimal RequiredBaseQuantity { get; set; } public decimal MovedBaseQuantity { get; set; } public decimal RemainingBaseQuantity { get; set; } [System.Text.Json.Serialization.JsonIgnore(Condition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)] public string? RowVersion { get; set; } }
public sealed class PutawayMovementDto { public int Id { get; set; } public int ItemId { get; set; } public string FromLocationCode { get; set; } = ""; public string ToLocationCode { get; set; } = ""; public decimal BaseQuantity { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class WarehouseLocationDto { public int Id { get; set; } public int WarehouseId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? StructurePath { get; set; } public string? StorageClass { get; set; } public decimal? MaxWeightKg { get; set; } public decimal? MaxVolumeM3 { get; set; } public decimal? MaxPalletEquivalent { get; set; } public string LocationType { get; set; } = ""; public bool IsActive { get; set; } public bool IsBlocked { get; set; } public bool IsPickable { get; set; } public bool IsReceivable { get; set; } public bool IsSystemManaged { get; set; } [System.Text.Json.Serialization.JsonIgnore(Condition=System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)] public string? RowVersion { get; set; } }
public sealed class CreateWarehouseLocationDto { public int WarehouseId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? StructurePath { get; set; } public string? StorageClass { get; set; } public decimal? MaxWeightKg { get; set; } public decimal? MaxVolumeM3 { get; set; } public decimal? MaxPalletEquivalent { get; set; } public string LocationType { get; set; } = ""; public bool IsPickable { get; set; } public bool IsReceivable { get; set; } }
public sealed class UpdateWarehouseLocationDto { public string Name { get; set; } = ""; public string? StructurePath { get; set; } public bool UpdateConstraints { get; set; } public string? StorageClass { get; set; } public decimal? MaxWeightKg { get; set; } public decimal? MaxVolumeM3 { get; set; } public decimal? MaxPalletEquivalent { get; set; } public bool IsActive { get; set; } public bool IsBlocked { get; set; } public bool IsPickable { get; set; } public bool IsReceivable { get; set; } public string RowVersion { get; set; } = ""; }
public sealed class WarehouseLocationCapacityDto { public int LocationId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string? StructurePath { get; set; } public string? StorageClass { get; set; } public decimal? MaxWeightKg { get; set; } public decimal? UsedWeightKg { get; set; } public decimal? MaxVolumeM3 { get; set; } public decimal? UsedVolumeM3 { get; set; } public decimal? MaxPalletEquivalent { get; set; } public decimal? UsedPalletEquivalent { get; set; } public bool ProfileIncomplete { get; set; } public bool CompatibilityConflict { get; set; } public bool IsActive { get; set; } public bool IsBlocked { get; set; } public string State { get; set; } = ""; }
public sealed class PutawayStateCommandDto { public string RowVersion { get; set; } = ""; public int? AssignedUserId { get; set; } public string? Reason { get; set; } }
public sealed class MovePutawayItemDto { public int ItemId { get; set; } public int DestinationLocationId { get; set; } public decimal Quantity { get; set; } public string UnitCode { get; set; } = ""; public string RowVersion { get; set; } = ""; }
