import type { BlueprintModule } from './erpWmsBlueprint';

export type CanonicalDocRepresentation = 'Capability-linked' | 'Platform / Governance';

export interface CanonicalDocumentationRow {
  spec: number;
  title: string;
  category: string;
  representation: CanonicalDocRepresentation;
  capabilityIds: string[];
}

export const canonicalSpecTitles: Record<number, string> = {
  1: "Business Rules & State Machine Specification",
  2: "Database Specification & DBML",
  3: "REST API & Backend Contract Specification",
  4: "Backend Architecture & Source Code Structure",
  5: "Implementation Blueprint & Codex Master Plan",
  6: "Test Strategy, QA Matrix & Production Readiness Checklist",
  7: "DevOps, CI/CD & Deployment Architecture",
  8: "Security, RBAC & Audit Specification",
  9: "Integration Architecture & Event Catalog",
  10: "Observability & Operations Runbook",
  11: "Backup, Disaster Recovery & Business Continuity",
  12: "Frontend & Mobile Technical Specification",
  13: "Reporting & Analytics Data Specification",
  14: "Data Migration & Go-Live Cutover Plan",
  15: "Architecture Decision Records (ADR)",
  16: "Data Dictionary & Table Catalog",
  17: "Permission Registry & Authorization Matrix",
  18: "Error Code Registry",
  19: "Domain Event & Integration Event Registry",
  20: "Configuration, Feature Flag & Reason Code Catalog",
  21: "API Examples & Integration Payload Cookbook",
  22: "Release Management & Production Deployment Checklist",
  23: "Production Operations Runbook & Incident Procedures",
  24: "Database Index, Query & Performance Catalog",
  25: "API Endpoint–Permission–State Matrix",
  26: "Test Case Catalog & Traceability Matrix",
  27: "Codex Execution Backlog & Feature Delivery Contract",
  28: "Inventory Engine Implementation Specification",
  29: "Inventory Ledger Posting Algorithm & Balance Projection",
  30: "Reservation & Allocation Engine Specification",
  31: "Inventory Concurrency, Locking & Idempotency Specification",
  32: "Reversal & Corrective Transaction Engine Specification",
  33: "SQL Server Migration & Inventory Core Rollout Plan",
  34: "Goods Receipt Posting & Inbound Execution Specification",
  35: "Putaway Engine & Location Assignment Specification",
  36: "Picking & Short Pick Resolution Engine Specification",
  37: "Handling Unit, Packing & Consolidation Engine Specification",
  38: "Shipment Loading, Dispatch & POD Specification",
  39: "Warehouse Transfer & In-Transit Inventory Specification",
  40: "Cycle Count & Inventory Adjustment Specification",
  41: "Inventory Status, QC Hold & Quarantine Specification",
  42: "Scrap, Disposal & Damaged Inventory Specification",
  43: "Customer Returns, RMA & Disposition Specification",
  44: "Replenishment & Min-Max Planning Specification",
  45: "Wave, Batch & Cluster Picking Specification",
  46: "Dock, Yard & Receiving Appointment Management Specification",
  47: "Cross-Docking Execution Specification",
  48: "Recall, Lot/Serial Traceability & Genealogy Specification",
  49: "Slotting Optimization & Storage Strategy Specification",
  50: "Task Interleaving, Labor & Shift Management Specification",
  51: "Business Rules Engine & Workflow Configuration Specification",
  52: "Kitting, Bundling & Assembly Execution Specification",
  53: "Value Added Services (VAS) Specification",
  54: "3PL & Multi-Owner Inventory Specification",
  55: "Consignment Inventory Specification",
  56: "Warehouse Billing & Charge Engine Specification",
  57: "Supplier Performance & Procurement Quality Specification",
  58: "Carrier Management & Shipment Tracking Specification",
  59: "Equipment & Material Handling Asset Management Specification",
  60: "Warehouse Calendar, Shift Capacity & Operational Planning Specification",
  61: "Notification, Alert & Escalation Engine Specification",
  62: "Document, Attachment & Evidence Management Specification",
  63: "Import, Export & Data Quality Framework Specification",
  64: "Label, GS1 & Print Architecture Specification",
  65: "Barcode & Scanning Standard Specification",
  66: "Mobile Offline, Retry & Synchronization Engine Specification",
  67: "Warehouse Map, Heatmap & Spatial Visualization Specification",
  68: "Dashboard & KPI Semantic Catalog",
  69: "Number Sequence & Document Numbering Engine Specification",
  70: "Approval Workflow Engine Specification",
  71: "Exception Management & Resolution Workflow Specification",
  72: "Backorder, Order Release & Cancellation Specification",
  73: "Inventory Ownership & Reclassification Specification",
  74: "Proof of Delivery, Delivery Failure & Shipment Completion Specification",
  75: "Integration Error Center & Retry Operations Specification",
  76: "Data Import Center & Controlled Bulk Operations Specification",
  77: "Inventory Freeze, Stock Lock & Operational Hold Engine Specification",
  78: "Expiry, Shelf-Life & FEFO Control Specification",
  79: "Recall Execution & Containment Workflow Specification",
  80: "Warehouse Task Engine & Work Queue Specification",
  81: "Labor Productivity, Operational SLA & Workforce KPI Catalog",
  82: "Inventory Snapshot, Reconciliation & Integrity Monitoring Specification",
  83: "Audit Retention, Compliance & Evidence Governance Specification",
  84: "Master Data Governance & Stewardship Specification",
  85: "Warehouse Location Capacity & Storage Constraint Engine Specification",
  86: "Advanced Allocation Policy & Inventory Selection Strategy Specification",
  87: "Order Priority, Fulfillment & Service-Level Policy Specification",
  88: "Inventory Availability Engine Specification",
  89: "ATP, CTP & Promise Date Specification",
  90: "Dock-to-Stock SLA & Receiving Performance Specification",
  91: "Order Cycle-Time & Fulfillment Analytics Specification",
  92: "Exception SLA, Escalation & Aging Policy Specification",
  93: "Data Archival, Partitioning & Historical Retention Strategy",
  94: "Caching Strategy & Read Model Consistency Specification",
  95: "Enterprise Search Architecture Specification",
  96: "File, Object Storage & Retention Lifecycle Specification",
  97: "API Rate Limiting, Abuse Protection & Request Governance Specification",
  98: "Feature Flag Governance & Safe Rollout Specification",
  99: "Multi-Company, Tenant Isolation & Data Segmentation Architecture",
  100: "Canonical Domain Model Specification",
  101: "Command, Query & Handler Catalog",
  102: "Repository, Unit of Work & Persistence Contract",
  103: "Background Worker & Asynchronous Processing Architecture",
  104: "Scheduler & Recurring Job Engine Specification",
  105: "System Bootstrap, Seed Data & Environment Initialization Specification",
  106: "API Versioning & Backward Compatibility Specification",
  107: "Event Schema Governance & Compatibility Specification",
  108: "Database Connection, Transaction & Resilience Specification",
  109: "Distributed Coordination & Locking Strategy Specification",
  110: "Health, Readiness & Liveness Endpoint Specification",
  111: "Secrets, Configuration Security & Environment Boundary Specification",
  112: "Authentication & Token Lifecycle Specification",
  113: "Session & Device Security Specification",
  114: "Webhook Security & Delivery Verification Specification",
  115: "Encryption, Key Management & Cryptographic Boundary Specification",
  116: "Data Classification, PII & Sensitive Data Handling Specification",
  117: "Security Threat Model & Abuse Case Catalog",
  118: "Performance & Capacity Model Specification",
  119: "Load, Stress & Soak Test Specification",
  120: "SQL Deadlock, Lock Ordering & Transaction Discipline Standard",
  121: "Observability Alert Catalog & Operational Threshold Specification",
  122: "SLO, SLA & Error Budget Framework",
  123: "Production Capacity, Scaling & Saturation Playbook",
  124: "Feature Dependency Map & Delivery Sequencing Specification",
  125: "Deployment Topology & Runtime Architecture Specification",
  126: "Environment Parity & Configuration Drift Standard",
  127: "Production Data Correction & Controlled Repair Framework",
  128: "Support & Administrative Tooling Specification",
  129: "Technical Debt Register & Architecture Fitness Function Catalog",
  130: "Architecture Review Checklist & Technical Governance Standard",
  131: "Code Review Standard & Pull Request Quality Gate",
  132: "Definition of Ready & Definition of Done Standard",
  133: "Engineering Release Evidence & Traceability Standard",
  134: "Production Readiness Review Template",
  135: "System Go-Live Acceptance Criteria & Launch Control Plan",
  136: "UAT Master Plan & Business Acceptance Strategy",
  137: "Role-Based UAT Script Catalog",
  138: "Training, SOP & Operational Enablement Framework",
  139: "Go-Live Hypercare Operations Plan",
  140: "Post-Go-Live Inventory Reconciliation & Verification Plan",
  141: "30/60/90-Day Stabilization & Optimization Plan",
  142: "Disaster Recovery Drill & Validation Plan",
  143: "Backup Restore Validation & Recovery Point Specification",
  144: "Failover, Failback & Service Recovery Procedure",
  145: "Business Continuity & Degraded Operation Mode Specification",
  146: "Offline Warehouse Operations & Deferred Synchronization Specification",
  147: "Recovery Reconciliation & Warehouse Reopening Procedure",
  148: "Warehouse Opening & Closing Procedure",
  149: "End-of-Day Processing & Operational Close Specification",
  150: "Period Close, Inventory Cutoff & Accounting Interface Specification",
  151: "Operational Reconciliation Dashboard Specification",
  152: "Data Integrity Repair Jobs & Projection Rebuild Specification",
  153: "Production Support Escalation & Ownership Matrix",
  154: "Inventory Costing Interface Specification",
  155: "Financial Reconciliation Specification",
  156: "Tax & Accounting Boundary Specification",
  157: "Intercompany & Inter-Warehouse Transfer Accounting Boundary",
  158: "Multi-Currency & Inventory Valuation Boundary Specification",
  159: "Finance Integration Error & Period Reconciliation Specification",
  160: "Purchase Order Integration Specification",
  161: "Sales Order Integration Specification",
  162: "ERP Master Data Synchronization Specification",
  163: "E-commerce & OMS Integration Specification",
  164: "Carrier & TMS Integration Specification",
  165: "EDI & External Partner API Integration Standard",
  166: "Webhook & Event Delivery Operations Specification",
  167: "Integration Contract Testing Specification",
  168: "API Gateway & Edge Architecture Specification",
  169: "Batch, File & Scheduled Integration Framework Specification",
  170: "External Partner Integration Onboarding Checklist",
  171: "Integration Reconciliation Dashboard & Control Specification",
  172: "Inventory Valuation Event Specification",
  173: "Warehouse Billing Reconciliation Specification",
  174: "Customer & Supplier SLA Contract Specification",
  175: "Operational Calendar Exception Specification",
  176: "Global Timezone, Business Date & Clock Standard",
  177: "Localization & Internationalization Architecture",
  178: "Multi-Warehouse Network Planning Specification",
  179: "Network Inventory Balancing Engine Specification",
  180: "Inter-Warehouse Replenishment Planning Specification",
  181: "Order Routing & Fulfillment Node Selection Specification",
  182: "Network Inventory Visibility & Global Availability Specification",
  183: "Distributed Warehouse Control Tower Specification",
  184: "Forecast & Demand Signal Integration Specification",
  185: "Safety Stock & Reorder Policy Engine Specification",
  186: "ABC/XYZ Inventory Classification Specification",
  187: "Slow-Moving, Non-Moving & Dead Stock Specification",
  188: "Inventory Optimization Policy Specification",
  189: "Network Rebalancing Simulation Specification",
  190: "Demand Forecast Accuracy & Bias Measurement Specification",
  191: "Replenishment Exception Management Specification",
  192: "Procurement Suggestion Engine Specification",
  193: "Inventory Risk Scoring Specification",
  194: "Warehouse Capacity Forecasting Specification",
  195: "Executive Supply Chain Control Tower KPI Specification",
  196: "Supplier Lead-Time Intelligence Specification",
  197: "Purchase Expedite & Defer Recommendation Specification",
  198: "Demand Spike & Anomaly Detection Specification",
  199: "Inventory Allocation Fairness Policy Specification",
  200: "Service-Level Segmentation Specification",
  201: "Scenario Planning & What-if Simulation Specification",
  202: "Automation Decision Boundary & Human-in-the-Loop Standard",
  203: "Decision Policy Registry & Version Governance Specification",
  204: "AI/ML Model Governance for WMS Decision Support",
  205: "Data Lineage, Metric Lineage & Semantic Traceability Specification",
  206: "Data Quality Scorecard & Governance Specification",
  207: "Reference Architecture Conformance Matrix",
  208: "Cross-Document Traceability Matrix",
  209: "Master Glossary & Ubiquitous Language",
  210: "System Capability Map & Module Ownership Specification",
  211: "Product Roadmap, Capability Maturity & Release Wave Plan",
  212: "Remaining Implementation Gap Register & Completion Criteria",
  213: "Documentation Governance, Review & Change Management Standard",
  214: "Master Technical Documentation Index & Reading Guide",
  215: "Frontend Architecture & Application Shell Specification",
  216: "UX Information Architecture & Navigation Specification",
  217: "ERP/WMS Design System & Visual Language Specification",
  218: "Desktop Screen Template & Interaction Pattern Catalog",
  219: "Data Table, Filter, Search & Bulk Action UX Specification",
  220: "Form, Validation & Transaction Entry UX Specification",
  221: "Workflow, Status, Approval & Exception UX Specification",
  222: "Inventory Visualization & Traceability UX Specification",
  223: "Mobile WMS Scan-First UX Specification",
  224: "Responsive, Accessibility & Internationalization UX Standard",
  225: "Frontend Permission, Security & Sensitive Action UX Specification",
  226: "Frontend Error, Concurrency, Idempotency & Recovery UX Specification",
  227: "Dashboard, KPI & Operational Analytics UX Specification",
  228: "UX Specification by Core Business Flow",
  229: "Screen Inventory & Coverage Matrix",
  230: "UX Writing, Labels, Terminology & Vietnamese Content Standard",
  231: "Frontend Performance & Large Dataset UX Specification",
  232: "Frontend Testing, Visual QA & Browser Regression Specification",
  233: "Figma Handoff, Component Mapping & Design-to-Code Standard",
  234: "UX/UI Definition of Ready, Definition of Done & Review Checklist",
  235: "Warehouse Automation, WCS/WES & Robotics Integration Specification",
  236: "RFID, IoT Sensor & Real-Time Capture Specification",
  237: "Voice Picking, Pick-to-Light & Assisted Picking Specification",
  238: "Cartonization, Cubing, Dimension & Packing Optimization Specification",
  239: "Load Planning, Trailer Utilization & Dock Loading Optimization Specification",
  240: "Hazardous Materials, Dangerous Goods & Restricted Storage Specification",
  241: "Cold Chain, Temperature-Controlled Inventory & Excursion Management Specification",
  242: "Catch Weight, Variable Weight & Dual-UOM Inventory Specification",
  243: "Kitting, Bundling, Assembly & De-kitting Specification",
  244: "Value-Added Services (VAS) Execution Specification",
  245: "Consignment, Vendor-Owned & Customer-Owned Inventory Specification",
  246: "3PL Customer Contract, Rating & Warehouse Billing Specification",
  247: "Returns Disposition, Refurbishment & Reverse Logistics Specification",
  248: "Yard Gate, Driver, Vehicle & Check-In/Check-Out Specification",
  249: "Warehouse Safety, Ergonomics & Operational Risk Control Specification",
  250: "Data Warehouse, BI Export & Analytical Platform Architecture",
  251: "CDC, Data Replication & Read Replica Specification",
  252: "Schema Migration, Zero-Downtime Compatibility & Database Evolution Standard",
  253: "API SDK, Client Contract & Frontend Data Access Standard",
  254: "Feature Telemetry, Product Analytics & UX Measurement Specification",
  255: "Browser, Device, Scanner & Peripheral Compatibility Matrix",
  256: "Localization Pack, Units, Locale & Regional Format Governance",
  257: "Legal Hold, eDiscovery & Regulatory Evidence Handling Specification",
  258: "Privacy Request & Data Subject Handling Boundary Specification",
  259: "Vendor, Dependency & Open-Source Governance Specification",
  260: "SBOM, Software Supply Chain & Artifact Provenance Specification",
  261: "Penetration Testing, Vulnerability Management & Security Verification Standard",
  262: "Chaos Engineering, Resilience Verification & Failure Injection Standard",
  263: "Performance Budget by Screen, API & Mobile Workflow Specification",
  264: "Tenant Provisioning, Company Onboarding & Warehouse Setup Runbook",
  265: "Warehouse Decommissioning, Tenant Offboarding & Data Exit Runbook",
  266: "Product Requirements Document (PRD) Standard & Feature Discovery Template",
  267: "Persona, Role, Job-to-be-Done & Operational Context Catalog",
  268: "User Journey, Service Blueprint & Cross-Channel Experience Specification",
  269: "UX Research, Usability Testing & Design Validation Standard",
  270: "Design Token, Component API & Storybook Governance Specification",
  271: "Notification Center, Inbox & Actionable Alert UX Specification",
  272: "Offline UX Conflict Resolution & Deferred Command Experience Specification",
  273: "Accessibility Conformance & Assistive Technology Test Catalog",
  274: "Enterprise Audit of Screen-to-API-to-Permission-to-State Coverage Matrix",
  275: "Final Documentation Coverage Audit & Completeness Register",
  276: "Administrative Console & Configuration UX Specification",
  277: "Warehouse Site Commissioning & Go-Live Readiness Specification",
  278: "Release Communication, Change Adoption & Operator Enablement Specification",
  279: "Identity Federation, SSO & Enterprise Access Integration Specification",
  280: "Evidence Export, Audit Package & Compliance Reporting Specification",
  281: "Manual Contingency Forms & Post-Outage Reconciliation Procedure",
  282: "UX Governance & Screen Matrix 229 Master Handoff Specification",
};

const categoryForSpec = (spec: number) => {
  if (spec <= 33) return 'Foundation / Core Design';
  if (spec <= 95) return 'WMS Domain';
  if (spec <= 129) return 'Platform Architecture';
  if (spec <= 159) return 'Delivery / Operations / Finance';
  if (spec <= 177) return 'Integration';
  if (spec <= 214) return 'Planning / Governance';
  if (spec <= 234) return 'Frontend / UX';
  if (spec <= 250) return 'Advanced WMS / Data';
  return 'Platform / Product Governance';
};

const referencedSpecs = (value: string) =>
  Array.from(new Set((value.match(/\d+/g) ?? []).map(Number)));

export const getCanonicalDocumentationRegister = (modules: BlueprintModule[]): CanonicalDocumentationRow[] => {
  const owners = new Map<number, string[]>();

  for (const module of modules) {
    for (const capability of module.capabilities) {
      for (const spec of referencedSpecs(capability.spec)) {
        const ids = owners.get(spec) ?? [];
        if (!ids.includes(capability.id)) ids.push(capability.id);
        owners.set(spec, ids);
      }
    }
  }

  return Object.entries(canonicalSpecTitles)
    .map(([spec, title]) => {
      const numericSpec = Number(spec);
      const capabilityIds = owners.get(numericSpec) ?? [];
      return {
        spec: numericSpec,
        title,
        category: categoryForSpec(numericSpec),
        representation: capabilityIds.length > 0 ? 'Capability-linked' as const : 'Platform / Governance' as const,
        capabilityIds,
      };
    })
    .sort((a, b) => a.spec - b.spec);
};
