import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, Eye, X } from 'lucide-react';
import apiClient from '../services/apiClient';
import { completeIdempotentAction, idempotencyHeaders } from '../services/idempotency';
import { validRejectReason } from '../services/approval';
import AccessibleDialog from '../components/AccessibleDialog';
import './Approvals.css';

type QueueItem = { documentType:string;documentId:number;documentCode:string;pendingState:string;creatorName:string;requestedAtUtc:string;warehouseName:string;destinationWarehouseName?:string;totalQuantity:number;canApprove:boolean;canReject:boolean;deniedReasonCode?:string };
type HistoryItem = { id:number;timestampUtc:string;actorName:string;displayAction:string;oldState?:string;newState?:string;result?:string;reason?:string;correlationId?:string };
type ApprovalDetail = { summary:QueueItem;note?:string;lines:{productCode:string;productName:string;unitName:string;quantity:number}[];history:HistoryItem[] };
type Page<T> = {items:T[];totalRecords:number;pageIndex:number;pageSize:number;totalPages:number};

const errorText = (error: unknown) => {
  const response = (error as {response?:{status?:number;data?:{message?:string;correlationId?:string};headers?:Record<string,string>}}).response;
  const correlation = response?.data?.correlationId ?? response?.headers?.['x-correlation-id'];
  const base = response?.status === 409 ? 'Chứng từ vừa được xử lý. Danh sách đã được tải lại.' : response?.status === 403 || response?.status === 404 ? 'Bạn không có quyền thực hiện thao tác này.' : response?.data?.message ?? 'Không thể xử lý yêu cầu.';
  return correlation ? `${base} Mã đối soát: ${correlation}` : base;
};

export default function Approvals() {
  const [page,setPage]=useState(1), [type,setType]=useState(''), [keyword,setKeyword]=useState('');
  const [warehouseId,setWarehouseId]=useState(''), [creatorId,setCreatorId]=useState(''), [fromUtc,setFromUtc]=useState(''), [toUtc,setToUtc]=useState('');
  const [data,setData]=useState<Page<QueueItem>>({items:[],totalRecords:0,pageIndex:1,pageSize:20,totalPages:0});
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<QueueItem|null>(null), [history,setHistory]=useState<HistoryItem[]>([]);
  const [detail,setDetail]=useState<ApprovalDetail|null>(null);
  const [rejecting,setRejecting]=useState(false), [reason,setReason]=useState('');
  const [approving,setApproving]=useState(false), [detailLoading,setDetailLoading]=useState(false);
  const submitting=useRef(false);
  const [dialogTrigger,setDialogTrigger]=useState<HTMLElement|null>(null);
  const closeDialog=useCallback(()=>{setSelected(null);setRejecting(false);setApproving(false);setReason('')},[]);
  const load=useCallback(async()=>{setLoading(true);try{const response=await apiClient.get<Page<QueueItem>>('/api/approvals/queue',{params:{pageIndex:page,pageSize:20,documentType:type||undefined,keyword:keyword||undefined,warehouseId:warehouseId||undefined,creatorId:creatorId||undefined,fromUtc:fromUtc?new Date(fromUtc).toISOString():undefined,toUtc:toUtc?new Date(toUtc).toISOString():undefined}});setData(response.data);}catch(e){setError(errorText(e));}finally{setLoading(false)}},[page,type,keyword,warehouseId,creatorId,fromUtc,toUtc]);
  useEffect(()=>{void load()},[load]);
  const open=async(item:QueueItem,trigger:HTMLElement)=>{setError('');setApproving(false);setRejecting(false);setDialogTrigger(trigger);setSelected(item);setHistory([]);setDetail(null);setDetailLoading(true);try{const r=await apiClient.get<ApprovalDetail>(`/api/approvals/${item.documentType}/${item.documentId}`);setDetail(r.data);setHistory(r.data.history)}catch(e){setError(errorText(e))}finally{setDetailLoading(false)}};
  const approve=async(item:QueueItem)=>{if(submitting.current||!item.canApprove)return;submitting.current=true;setError('');setBusy(true);const key=`approve:${item.documentType}:${item.documentId}`;try{const routes:Record<string,string>={ImportReceipt:`/api/ImportReceipts/${item.documentId}/approve`,ExportReceipt:`/api/ExportReceipts/${item.documentId}/approve`,StockTransfer:`/api/stock-transfers/${item.documentId}/approve`,Stocktake:`/api/Stocktakes/${item.documentId}/approve`};await apiClient.post(routes[item.documentType],null,{headers:idempotencyHeaders(key)});completeIdempotentAction(key);setSelected(null);await load()}catch(e){setError(errorText(e));if((e as {response?:{status?:number}}).response?.status===409)await load()}finally{submitting.current=false;setBusy(false)}};
  const reject=async()=>{if(!selected||submitting.current||!selected.canReject)return;const cleaned=reason.trim();if(!validRejectReason(reason))return;submitting.current=true;setError('');setBusy(true);const key=`reject:${selected.documentType}:${selected.documentId}`;try{await apiClient.post(`/api/approvals/${selected.documentType}/${selected.documentId}/reject`,{reason:cleaned},{headers:idempotencyHeaders(key)});completeIdempotentAction(key);setRejecting(false);setSelected(null);setReason('');await load()}catch(e){setError(errorText(e));if((e as {response?:{status?:number}}).response?.status===409)await load()}finally{submitting.current=false;setBusy(false)}};
  return <section className="approval-page">
    <header><div><h1>Hàng đợi phê duyệt</h1><p>{data.totalRecords} chứng từ đang chờ trong phạm vi của bạn</p></div></header>
    {error&&<div className="approval-error" role="alert">{error}</div>}
    <div className="approval-filters"><select aria-label="Loại chứng từ" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">Tất cả loại</option><option value="ImportReceipt">Nhập kho</option><option value="ExportReceipt">Xuất kho</option><option value="StockTransfer">Điều chuyển</option><option value="Stocktake">Kiểm kê</option></select><input aria-label="Tìm mã chứng từ" value={keyword} onChange={e=>{setKeyword(e.target.value);setPage(1)}} placeholder="Tìm theo mã" /><input aria-label="Mã kho" type="number" min="1" value={warehouseId} onChange={e=>{setWarehouseId(e.target.value);setPage(1)}} placeholder="ID kho" /><input aria-label="Mã người tạo" type="number" min="1" value={creatorId} onChange={e=>{setCreatorId(e.target.value);setPage(1)}} placeholder="ID người tạo" /><input aria-label="Từ ngày" type="datetime-local" value={fromUtc} onChange={e=>{setFromUtc(e.target.value);setPage(1)}} /><input aria-label="Đến ngày" type="datetime-local" value={toUtc} onChange={e=>{setToUtc(e.target.value);setPage(1)}} /></div>
    {loading?<div className="approval-state">Đang tải...</div>:data.items.length===0?<div className="approval-state">Không có chứng từ chờ duyệt.</div>:<div className="approval-table"><table><thead><tr><th>Loại</th><th>Mã</th><th>Kho</th><th>Người tạo</th><th>Thời gian gửi</th><th>Trạng thái</th><th>Hành động</th></tr></thead><tbody>{data.items.map(item=><tr key={`${item.documentType}-${item.documentId}`}><td>{item.documentType}</td><td>{item.documentCode}</td><td>{item.warehouseName}{item.destinationWarehouseName&&` → ${item.destinationWarehouseName}`}</td><td>{item.creatorName}</td><td>{new Date(item.requestedAtUtc).toLocaleString()}</td><td>Chờ duyệt</td><td><button title="Xem chi tiết" onClick={e=>void open(item,e.currentTarget)}><Eye size={17}/></button>{item.canApprove&&<button title="Duyệt" disabled={busy} onClick={e=>{setError('');setDialogTrigger(e.currentTarget);setSelected(item);setRejecting(false);setApproving(true)}}><Check size={17}/></button>}{item.canReject&&<button title="Từ chối" disabled={busy} onClick={e=>{setError('');setApproving(false);setReason('');setDialogTrigger(e.currentTarget);setSelected(item);setRejecting(true)}}><X size={17}/></button>}</td></tr>)}</tbody></table></div>}
    <nav className="approval-pagination"><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Trước</button><span>Trang {data.pageIndex}/{Math.max(1,data.totalPages)}</span><button disabled={page>=data.totalPages||loading} onClick={()=>setPage(p=>p+1)}>Sau</button></nav>
    {selected&&<AccessibleDialog titleId="approval-title" busy={busy} onClose={closeDialog} returnFocusTo={dialogTrigger}><h2 id="approval-title">{selected.documentCode}</h2><p>{selected.documentType} · {selected.warehouseName}</p>{rejecting?<><label>Lý do từ chối<textarea disabled={busy} data-initial-focus maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><small>{reason.length}/500</small></>:approving?<p>Xác nhận duyệt chứng từ này?</p>:detailLoading?<p role="status">Đang tải chi tiết...</p>:<>{detail?.note&&<p><strong>Ghi chú:</strong> {detail.note}</p>}{detail&&detail.lines.length>0&&<table><thead><tr><th>Sản phẩm</th><th>Đơn vị</th><th>Số lượng</th></tr></thead><tbody>{detail.lines.map(line=><tr key={line.productCode}><td>{line.productCode} · {line.productName}</td><td>{line.unitName}</td><td>{line.quantity}</td></tr>)}</tbody></table>}<h3>Lịch sử phê duyệt</h3>{history.length===0?<p>Chưa có lịch sử.</p>:<ol>{history.map(h=><li key={h.id}><strong>{h.displayAction}</strong> · {h.actorName} · {new Date(h.timestampUtc).toLocaleString()}<div>{h.oldState} → {h.newState}</div>{h.reason&&<p>{h.reason}</p>}{h.correlationId&&<code>{h.correlationId}</code>}</li>)}</ol>}</>}{error&&<p role="alert">{error}</p>}<footer><button data-initial-focus={approving||undefined} disabled={busy} onClick={closeDialog}>Đóng</button>{approving&&<button disabled={busy} onClick={()=>void approve(selected)}>Xác nhận duyệt</button>}{rejecting&&<button className="danger" disabled={busy||!validRejectReason(reason)} onClick={()=>void reject()}>Xác nhận từ chối</button>}</footer></AccessibleDialog>}
  </section>;
}
