import type { ReactNode } from 'react';
import { ClipboardCheck, LockKeyhole, PackageX, RotateCcw, Siren, Trash2 } from 'lucide-react';
import './QualityReturnsCapabilityMock.css';

type Props={capabilityId?:string}; type Tone='success'|'warning'|'danger'|'neutral';
const Badge=({tone,children}:{tone:Tone;children:ReactNode})=><span className={'qr-badge '+tone}>{children}</span>;
const Header=({id,title,description,icon}:{id:string;title:string;description:string;icon:ReactNode})=>(
<header className="qr-header"><div className="qr-title"><span className="qr-icon" aria-hidden="true">{icon}</span><div><span className="qr-kicker">CHẤT LƯỢNG & TRẢ HÀNG • {id} • MÔ PHỎNG GIAO DIỆN</span><h2>{title}</h2></div></div><p>{description}</p><div className="qr-scope"><Badge tone="neutral">Chỉ đọc</Badge><span>Không gọi API hệ thống thật • Không ghi tồn kho • Không giả ghi sổ/phân loại xử lý</span></div></header>
);
const Metrics=({items}:{items:[string,string,string][]})=><div className="qr-metrics">{items.map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>;

const Qc=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-01"><Header id="QR-01" title="Trung tâm công việc kiểm tra chất lượng" description="Hàng đợi kiểm tra theo ưu tiên, tiêu chí, bằng chứng và phân loại xử lý; trường hợp không đạt phải đi qua phân loại xử lý thay vì tự mở khóa." icon={<ClipboardCheck size={20}/>}/><Metrics items={[[ 'Hàng đợi','12','3 ưu tiên cao'],['Phiếu kiểm tra','QC-2026-3011','GR-2026-1045'],['Bằng chứng','3 mục','2 ảnh • 1 ghi chú'],['SLA','24 phút','Trước khi leo thang']]}/><div className="qr-grid"><article><strong>Tình trạng bao bì</strong><span>Đạt • 12/12 mẫu</span><Badge tone="success">ĐẠT</Badge></article><article><strong>Niêm phong / nhãn khớp</strong><span>Đạt • LOT-261004-A</span><Badge tone="success">ĐẠT</Badge></article><article><strong>Nhiễm bẩn quan sát được</strong><span>1 phát hiện cần phân loại xử lý</span><Badge tone="danger">KHÔNG ĐẠT</Badge></article></div><div className="qr-callout warning"><strong>Cần phân loại xử lý</strong><span>Tiêu chí không đạt không được tự động mở tồn kho; phải giữ bằng chứng, lý do và quyết định phân loại xử lý.</span></div></section>
);

const Hold=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-02"><Header id="QR-02" title="Điều kiện giữ QC / Cách ly" description="Mô phỏng chính sách trạng thái chặn giữ/phân bổ/lấy hàng khi tồn đang QC_HOLD hoặc QUARANTINE." icon={<LockKeyhole size={20}/>}/><Metrics items={[[ 'SKU / Lô','SKU-1001','LOT-1001-260930'],['Số lượng','96 Cái','WH-HCM-01'],['Trạng thái','QC_HOLD','QUALITY_REVIEW'],['Điều kiện','0 Cái','Khả dụng cho xuất kho']]}/><div className="qr-policy-table"><div><span>Giữ hàng</span><Badge tone="danger">Bị chặn</Badge></div><div><span>Phân bổ</span><Badge tone="danger">Bị chặn</Badge></div><div><span>Lấy hàng</span><Badge tone="danger">Bị chặn</Badge></div><div><span>Kiểm tra QC</span><Badge tone="success">Được phép</Badge></div></div><div className="qr-callout warning"><strong>Rào chắn mở trạng thái</strong><span>Chỉ mở về AVAILABLE khi phân loại xử lý/bằng chứng đạt chính sách; không sửa trạng thái trực tiếp để vượt trạng thái giữ.</span></div></section>
);

const Damage=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-03"><Header id="QR-03" title="Phân loại xử lý tồn kho hư hỏng" description="DAMAGE_FOUND dùng chung từ tiếp nhận, cất hàng, lấy hàng, điều chuyển, kiểm kê và trả hàng." icon={<PackageX size={20}/>}/><Metrics items={[[ 'Nguồn','PUTAWAY-2026-4110','RECEIVING-01'],['SKU / Lô','SKU-1001','LOT-1001-260930'],['Thực nhận','24 Cái','Số lượng đủ điều kiện'],['Hư hỏng','4 Cái','PACKAGE_TORN']]}/><div className="qr-flow"><div><span>1</span><strong>Báo cáo</strong><small>Ghi nhận nguồn + lý do</small></div><div><span>2</span><strong>Cách ly</strong><small>Ngăn đủ điều kiện xuất kho</small></div><div><span>3</span><strong>Rà soát QC</strong><small>Bằng chứng + disposition</small></div><div><span>4</span><strong>Xử lý</strong><small>Nhập lại / sửa chữa / tiêu hủy</small></div></div><div className="qr-callout warning"><strong>Số lượng guard</strong><span>Hư hỏng quantity không thể vượt observed/eligible quantity tại stock identity gốc.</span></div></section>
);

const Return=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-04"><Header id="QR-04" title="Bàn làm việc trả hàng khách / RMA" description="Nhận hàng trả → kiểm tra → phân loại xử lý → ghi sổ Phiếu nhận trả hàng rõ ràng, giữ liên kết về lô giao hàng gốc." icon={<RotateCcw size={20}/>}/><Metrics items={[[ 'RMA','RMA-2026-1882','Đã ủy quyền'],['Lô giao hàng','SHP-2026-5108','Xuất kho gốc'],['Số lượng trả','2 Cái','Đã xác thực sê-ri'],['Ảnh hưởng tồn kho','0','Cho tới khi ghi sổ hàng trả']]}/><div className="qr-grid"><article><strong>RESTOCK</strong><span>Có thể bán sau kiểm tra</span><Badge tone="success">Đủ điều kiện</Badge></article><article><strong>REPAIR</strong><span>Chuyển sang quy trình sửa chữa</span><Badge tone="warning">Có điều kiện</Badge></article><article><strong>SCRAP</strong><span>Cần phê duyệt + ghi sổ</span><Badge tone="danger">Có kiểm soát</Badge></article></div><div className="qr-callout warning"><strong>Ranh giới ghi sổ hàng trả</strong><span>RECEIVED/INSPECTED không tăng OnHand. Chỉ ghi sổ Phiếu nhận trả hàng mới tạo biến động tồn kho.</span></div></section>
);

const Thu hồi=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-05"><Header id="QR-05" title="Phạm vi ảnh hưởng & kiểm soát thu hồi" description="Truy phạm vi tồn tại kho + đã giao theo lô/sê-ri/chứng từ, chặn tồn kho và theo dõi ảnh hưởng khách hàng." icon={<Siren size={20}/>}/><Metrics items={[[ 'Thu hồi','RCL-2026-004','OPEN'],['Lot','LOT-1001-260930','Lô bị ảnh hưởng'],['Trong kho','420 Cái','3 kho'],['Đã giao','180 Cái','12 khách hàng']]}/><div className="qr-recall"><article><strong>WH-HCM-01</strong><span>220 Cái</span><Badge tone="danger">BLOCKED</Badge></article><article><strong>WH-DN-01</strong><span>140 Cái</span><Badge tone="danger">BLOCKED</Badge></article><article><strong>WH-HN-01</strong><span>60 Cái</span><Badge tone="warning">Chờ truy vết</Badge></article><article><strong>Phạm vi khách hàng</strong><span>12 lô giao hàng</span><Badge tone="warning">Thông báo</Badge></article></div><div className="qr-callout danger"><strong>Độ đầy đủ phạm vi</strong><span>Không đóng thu hồi khi phả hệ còn thiếu liên kết giao hàng/trả hàng/khách hàng.</span></div></section>
);

const Tiêu hủy=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-06"><Header id="QR-06" title="Phê duyệt tiêu hủy & ghi sổ tồn kho" description="Phê duyệt + bằng chứng + ghi sổ tiêu hủy rõ ràng; phê duyệt không tự làm giảm tồn." icon={<Trash2 size={20}/>}/><Metrics items={[[ 'Tiêu hủy','SCR-2026-0081','IRREPAIRABLE_DAMAGE'],['Số lượng','4 Cái','SKU-1001'],['Bằng chứng','Đầy đủ','Ảnh + ghi chú'],['Người phê duyệt','U-SUPERVISOR','Người khác thực hiện']]}/><div className="qr-flow"><div><span>1</span><strong>DRAFT</strong><small>Lý do + bằng chứng</small></div><div><span>2</span><strong>SUBMITTED</strong><small>Kiểm tra chính sách / SoD</small></div><div><span>3</span><strong>APPROVED</strong><small>Không tác động sổ cái</small></div><div><span>4</span><strong>POSTED</strong><small>Tồn kho -4 đúng một lần</small></div></div><div className="qr-callout danger"><strong>Rào chắn ghi sổ</strong><span>Chỉ POST tiêu hủy mới giảm tồn kho; thử lại phải idempotent, có sổ cái bất biến + bằng chứng kiểm toán.</span></div></section>
);

const QualityReturnsCapabilityMock=({capabilityId}:Props)=>{if(capabilityId==='QR-01')return <Qc/>;if(capabilityId==='QR-02')return <Hold/>;if(capabilityId==='QR-03')return <Damage/>;if(capabilityId==='QR-04')return <Return/>;if(capabilityId==='QR-05')return <Thu hồi/>;if(capabilityId==='QR-06')return <Tiêu hủy/>;return null;};
export default QualityReturnsCapabilityMock;