import type { ReactNode } from 'react';
import { ClipboardCheck, LockKeyhole, PackageX, RotateCcw, Siren, Trash2 } from 'lucide-react';
import './QualityReturnsCapabilityMock.css';

type Props={capabilityId?:string}; type Tone='success'|'warning'|'danger'|'neutral';
const Badge=({tone,children}:{tone:Tone;children:ReactNode})=><span className={'qr-badge '+tone}>{children}</span>;
const Header=({id,title,description,icon}:{id:string;title:string;description:string;icon:ReactNode})=>(
<header className="qr-header"><div className="qr-title"><span className="qr-icon" aria-hidden="true">{icon}</span><div><span className="qr-kicker">QUALITY & RETURNS • {id} • FRONTEND MOCK</span><h2>{title}</h2></div></div><p>{description}</p><div className="qr-scope"><Badge tone="neutral">Read-only</Badge><span>Không gọi API production • Không ghi inventory • Không giả posting/disposition</span></div></header>
);
const Metrics=({items}:{items:[string,string,string][]})=><div className="qr-metrics">{items.map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>;

const Qc=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-01"><Header id="QR-01" title="QC Inspection Work Center" description="Queue inspection theo priority, criteria, evidence và disposition; failure phải đi disposition thay vì tự release." icon={<ClipboardCheck size={20}/>}/><Metrics items={[[ 'Queue','12','3 high priority'],['Inspection','QC-2026-3011','GR-2026-1045'],['Evidence','3 items','2 photos • 1 note'],['SLA','24 phút','Before escalation']]}/><div className="qr-grid"><article><strong>Packaging integrity</strong><span>Pass • 12/12 samples</span><Badge tone="success">PASS</Badge></article><article><strong>Seal / label match</strong><span>Pass • LOT-261004-A</span><Badge tone="success">PASS</Badge></article><article><strong>Visual contamination</strong><span>1 finding needs disposition</span><Badge tone="danger">FAIL</Badge></article></div><div className="qr-callout warning"><strong>Disposition required</strong><span>Failed criteria không được tự động release inventory; phải giữ evidence, reason và disposition decision.</span></div></section>
);

const Hold=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-02"><Header id="QR-02" title="QC Hold / Quarantine Eligibility" description="Mock status policy chặn reserve/allocate/pick khi stock đang QC_HOLD hoặc QUARANTINE." icon={<LockKeyhole size={20}/>}/><Metrics items={[[ 'SKU / Lot','SKU-1001','LOT-1001-260930'],['Quantity','96 Cái','WH-HCM-01'],['Status','QC_HOLD','QUALITY_REVIEW'],['Eligibility','0 Cái','Available for outbound']]}/><div className="qr-policy-table"><div><span>Reserve</span><Badge tone="danger">Blocked</Badge></div><div><span>Allocate</span><Badge tone="danger">Blocked</Badge></div><div><span>Pick</span><Badge tone="danger">Blocked</Badge></div><div><span>QC inspect</span><Badge tone="success">Allowed</Badge></div></div><div className="qr-callout warning"><strong>Release guard</strong><span>Chỉ release về AVAILABLE khi disposition/evidence đạt policy; không sửa status trực tiếp để vượt hold.</span></div></section>
);

const Damage=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-03"><Header id="QR-03" title="Damaged Inventory Triage" description="DAMAGE_FOUND dùng chung từ receiving, putaway, picking, transfer, count và returns." icon={<PackageX size={20}/>}/><Metrics items={[[ 'Source','PUTAWAY-2026-4110','RECEIVING-01'],['SKU / Lot','SKU-1001','LOT-1001-260930'],['Observed','24 Cái','Eligible quantity'],['Damaged','4 Cái','PACKAGE_TORN']]}/><div className="qr-flow"><div><span>1</span><strong>Report</strong><small>Capture source + reason</small></div><div><span>2</span><strong>Isolate</strong><small>Prevent outbound eligibility</small></div><div><span>3</span><strong>QC review</strong><small>Evidence + disposition</small></div><div><span>4</span><strong>Resolve</strong><small>Restock / repair / scrap</small></div></div><div className="qr-callout warning"><strong>Quantity guard</strong><span>Damaged quantity không thể vượt observed/eligible quantity tại stock identity gốc.</span></div></section>
);

const Return=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-04"><Header id="QR-04" title="Customer Return / RMA Workbench" description="Receive return → inspect → disposition → explicit Return Receipt POST, giữ linkage về shipment gốc." icon={<RotateCcw size={20}/>}/><Metrics items={[[ 'RMA','RMA-2026-1882','Authorized'],['Shipment','SHP-2026-5108','Original outbound'],['Return qty','2 Cái','Serial validated'],['Inventory effect','0','Until Return POST']]}/><div className="qr-grid"><article><strong>RESTOCK</strong><span>Sellable after inspection</span><Badge tone="success">Eligible</Badge></article><article><strong>REPAIR</strong><span>Route to repair workflow</span><Badge tone="warning">Conditional</Badge></article><article><strong>SCRAP</strong><span>Requires approval + posting</span><Badge tone="danger">Controlled</Badge></article></div><div className="qr-callout warning"><strong>Return posting boundary</strong><span>RECEIVED/INSPECTED không tăng On Hand. Chỉ Return Receipt POST mới tạo inventory movement.</span></div></section>
);

const Recall=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-05"><Header id="QR-05" title="Recall Exposure & Control" description="Trace in-stock + shipped exposure theo lot/serial/document, block inventory và theo dõi customer impact." icon={<Siren size={20}/>}/><Metrics items={[[ 'Recall','RCL-2026-004','OPEN'],['Lot','LOT-1001-260930','Affected lot'],['In stock','420 Cái','3 warehouses'],['Shipped','180 Cái','12 customers']]}/><div className="qr-recall"><article><strong>WH-HCM-01</strong><span>220 Cái</span><Badge tone="danger">BLOCKED</Badge></article><article><strong>WH-DN-01</strong><span>140 Cái</span><Badge tone="danger">BLOCKED</Badge></article><article><strong>WH-HN-01</strong><span>60 Cái</span><Badge tone="warning">Trace pending</Badge></article><article><strong>Customer exposure</strong><span>12 shipments</span><Badge tone="warning">Notify</Badge></article></div><div className="qr-callout danger"><strong>Scope completeness</strong><span>Không close recall khi genealogy còn thiếu shipment/return/customer linkage.</span></div></section>
);

const Scrap=()=>(
<section className="qr-capability" data-testid="quality-capability-mock-QR-06"><Header id="QR-06" title="Scrap Approval & Inventory Posting" description="Approval + evidence + explicit scrap posting; approval không tự làm giảm tồn." icon={<Trash2 size={20}/>}/><Metrics items={[[ 'Scrap','SCR-2026-0081','IRREPAIRABLE_DAMAGE'],['Quantity','4 Cái','SKU-1001'],['Evidence','Complete','Photo + note'],['Approver','U-SUPERVISOR','Different actor']]}/><div className="qr-flow"><div><span>1</span><strong>DRAFT</strong><small>Reason + evidence</small></div><div><span>2</span><strong>SUBMITTED</strong><small>Policy / SoD check</small></div><div><span>3</span><strong>APPROVED</strong><small>Ledger-neutral</small></div><div><span>4</span><strong>POSTED</strong><small>Inventory -4 exactly once</small></div></div><div className="qr-callout danger"><strong>Posting guard</strong><span>Chỉ POST scrap mới giảm inventory; retry phải idempotent, có immutable ledger + audit evidence.</span></div></section>
);

const QualityReturnsCapabilityMock=({capabilityId}:Props)=>{if(capabilityId==='QR-01')return <Qc/>;if(capabilityId==='QR-02')return <Hold/>;if(capabilityId==='QR-03')return <Damage/>;if(capabilityId==='QR-04')return <Return/>;if(capabilityId==='QR-05')return <Recall/>;if(capabilityId==='QR-06')return <Scrap/>;return null;};
export default QualityReturnsCapabilityMock;