const typeLabels: Record<string, string> = {
  '3PL Billing': 'Tính phí 3PL',
  '3PL Contract / Rating': 'Hợp đồng / tính giá 3PL',
  'ABC / XYZ Classification': 'Phân loại ABC / XYZ',
  'ASN': 'Thông báo giao hàng trước (ASN)',
  'ATP / CTP': 'Khả dụng / khả năng đáp ứng (ATP / CTP)',
  'Activity Feed': 'Dòng hoạt động',
  'Adjustment': 'Điều chỉnh',
  'Aging': 'Tuổi tồn kho',
  'Alert': 'Cảnh báo',
  'Allocation': 'Phân bổ',
  'Allocation Fairness': 'Công bằng phân bổ',
  'Appointment': 'Lịch hẹn',
  'Approval': 'Phê duyệt',
  'Assisted Picking': 'Lấy hàng có hỗ trợ',
  'Audit': 'Kiểm toán',
  'BI Export': 'Xuất dữ liệu BI',
  'Backup': 'Sao lưu',
  'Bin': 'Ô chứa',
  'Business Rule': 'Quy tắc nghiệp vụ',
  'Calendar Exception': 'Ngoại lệ lịch vận hành',
  'Capacity': 'Sức chứa',
  'Capacity Forecast': 'Dự báo sức chứa',
  'Carton': 'Thùng carton',
  'Cartonization': 'Tối ưu đóng thùng',
  'Catch Weight': 'Trọng lượng biến đổi',
  'Cold Chain Excursion': 'Vượt ngưỡng chuỗi lạnh',
  'Consignment Inventory': 'Tồn kho ký gửi',
  'Controlled Repair': 'Sửa lỗi có kiểm soát',
  'Count Task': 'Nhiệm vụ kiểm kê',
  'Cross-dock': 'Trung chuyển trực tiếp',
  'Cycle Count': 'Kiểm kê chu kỳ',
  'Dead Letter': 'Thông điệp lỗi cuối',
  'Decision Policy': 'Chính sách quyết định',
  'Demand Anomaly': 'Bất thường nhu cầu',
  'Dock': 'Cửa kho',
  'Dock Door': 'Cửa kho',
  'Equipment': 'Thiết bị',
  'Evidence': 'Bằng chứng',
  'Exception Handling': 'Xử lý ngoại lệ',
  'Expedite / Defer Recommendation': 'Đề xuất thúc đẩy / trì hoãn',
  'Feature Telemetry': 'Đo lường sử dụng chức năng',
  'Finance / Costing Interface': 'Giao diện tài chính / tính giá',
  'Forecast Accuracy': 'Độ chính xác dự báo',
  'Forecast Signal': 'Tín hiệu dự báo',
  'Fulfillment Routing': 'Định tuyến đáp ứng đơn hàng',
  'Full Count': 'Kiểm kê toàn bộ',
  'Global Search': 'Tìm kiếm toàn hệ thống',
  'Goods Receipt': 'Phiếu nhập kho',
  'Hazmat Policy': 'Chính sách hàng nguy hiểm',
  'Health Check': 'Kiểm tra tình trạng hệ thống',
  'Import Batch': 'Lô nhập dữ liệu',
  'Inbox': 'Hộp thư tích hợp',
  'Integration Reconciliation': 'Đối chiếu tích hợp',
  'Inter-Warehouse Replenishment': 'Bổ sung hàng liên kho',
  'Inventory Balance': 'Số dư tồn kho',
  'Inventory Lock': 'Khóa tồn kho',
  'Inventory Optimization': 'Tối ưu tồn kho',
  'Inventory Reconciliation': 'Đối chiếu tồn kho',
  'Inventory Risk Score': 'Điểm rủi ro tồn kho',
  'Inventory Snapshot': 'Ảnh chụp tồn kho',
  'Inventory Turnover': 'Vòng quay tồn kho',
  'Kitting Order': 'Lệnh lắp bộ',
  'Label': 'Nhãn',
  'Ledger': 'Sổ cái',
  'Legal Hold': 'Giữ dữ liệu pháp lý',
  'Load Plan': 'Kế hoạch xếp hàng',
  'Localization Pack': 'Gói bản địa hóa',
  'Lot': 'Lô',
  'Network Balancing': 'Cân bằng mạng lưới',
  'Network Planning': 'Lập kế hoạch mạng lưới',
  'Network Rebalancing Simulation': 'Mô phỏng cân bằng lại mạng lưới',
  'Notification': 'Thông báo',
  'Number Sequence': 'Dãy số chứng từ',
  'Offline Queue': 'Hàng đợi ngoại tuyến',
  'Outbox': 'Hộp thư đi tích hợp',
  'Packaging Type': 'Loại bao bì',
  'Pallet': 'Pallet',
  'Partner SLA': 'SLA đối tác',
  'Permission': 'Quyền',
  'Picking': 'Lấy hàng',
  'Picking Task': 'Nhiệm vụ lấy hàng',
  'Privacy Request': 'Yêu cầu quyền riêng tư',
  'Procurement Suggestion': 'Đề xuất mua hàng',
  'Product Lookup': 'Tra cứu sản phẩm',
  'Proof of Delivery': 'Bằng chứng giao hàng',
  'Putaway': 'Cất hàng',
  'QC Inspection': 'Kiểm tra chất lượng',
  'Quarantine': 'Cách ly',
  'RFID Capture': 'Ghi nhận RFID',
  'Receiving Task': 'Nhiệm vụ tiếp nhận',
  'Reconciliation': 'Đối chiếu',
  'Recovery Reconciliation': 'Đối chiếu sau phục hồi',
  'Replenishment': 'Bổ sung hàng',
  'Replenishment Exception': 'Ngoại lệ bổ sung hàng',
  'Reservation': 'Giữ hàng',
  'Return': 'Hàng trả',
  'Reverse Logistics': 'Logistics ngược',
  'Safety Rule': 'Quy tắc an toàn',
  'Safety Stock Policy': 'Chính sách tồn kho an toàn',
  'Sales Order': 'Đơn bán hàng',
  'Scrap': 'Tiêu hủy',
  'Serial': 'Sê-ri',
  'Service-Level Segment': 'Phân khúc mức dịch vụ',
  'Shipment': 'Lô giao hàng',
  'Shipment Tracking': 'Theo dõi giao hàng',
  'Slotting': 'Tối ưu vị trí lưu trữ',
  'Supplier Lead-Time Intelligence': 'Phân tích thời gian cung ứng',
  'Support Tooling': 'Công cụ hỗ trợ',
  'Sync Error': 'Lỗi đồng bộ',
  'Transfer': 'Điều chuyển',
  'UOM': 'Đơn vị tính',
  'User': 'Người dùng',
  'VAS Order': 'Lệnh dịch vụ gia tăng',
  'WCS / Robotics Job': 'Công việc WCS / Robot',
  'Warehouse': 'Kho',
  'Warehouse Offboarding': 'Ngừng vận hành kho',
  'What-if Scenario': 'Kịch bản giả định',
  'Work Queue': 'Hàng đợi công việc',
  'Yard Slot': 'Vị trí sân bãi',
};

const statusLabels: Record<string, string> = {
  ACTIVE: 'Đang hoạt động',
  Active: 'Đang hoạt động',
  ALLOCATED: 'Đã phân bổ',
  APPROVED: 'Đã phê duyệt',
  AVAILABLE: 'Khả dụng',
  Available: 'Khả dụng',
  A_X: 'Nhóm A/X',
  CAPTURED: 'Đã ghi nhận',
  CHECKED_IN: 'Đã vào cổng',
  COUNTING: 'Đang kiểm đếm',
  CRITICAL: 'Khẩn cấp',
  DELIVERED: 'Đã giao',
  DISPOSITION_PENDING: 'Chờ quyết định xử lý',
  DRAFT: 'Bản nháp',
  ENABLED: 'Đã bật',
  EXPEDITE: 'Cần thúc đẩy',
  Expected: 'Dự kiến',
  FAILED: 'Thất bại',
  HEALTHY: 'Bình thường',
  HIGH: 'Cao',
  IMMUTABLE: 'Bất biến',
  INGESTED: 'Đã tiếp nhận dữ liệu',
  INSPECTION: 'Đang kiểm tra',
  INVESTIGATING: 'Đang điều tra',
  IN_PROGRESS: 'Đang xử lý',
  IN_TRANSIT: 'Đang vận chuyển',
  LOADED: 'Đã xếp hàng',
  MATCHED: 'Đã khớp',
  MEASURED: 'Đã đo',
  MISMATCH: 'Không khớp',
  NO_SOURCE: 'Không có nguồn',
  OCCUPIED: 'Đang sử dụng',
  Occupied: 'Đang sử dụng',
  OPEN: 'Đang mở',
  PACKED: 'Đã đóng gói',
  PENDING: 'Đang chờ',
  PENDING_APPROVAL: 'Chờ phê duyệt',
  PENDING_SYNC: 'Chờ đồng bộ',
  PLANNED: 'Đã lập kế hoạch',
  POSTED: 'Đã ghi sổ',
  PRINTED: 'Đã in',
  PROCESSED: 'Đã xử lý',
  PROMISE_READY: 'Sẵn sàng cam kết',
  PROPOSED: 'Đã đề xuất',
  PUBLISHED: 'Đã công bố',
  QC_HOLD: 'Chờ kiểm tra chất lượng',
  QC_PENDING: 'Chờ kiểm tra chất lượng',
  QUARANTINE_REQUIRED: 'Yêu cầu cách ly',
  READY: 'Sẵn sàng',
  READY_TO_POST: 'Sẵn sàng ghi sổ',
  READY_TO_REOPEN: 'Sẵn sàng mở lại',
  RECEIVED: 'Đã nhận',
  RECEIVING: 'Đang tiếp nhận',
  RECOMMENDED: 'Được đề xuất',
  RECONCILED: 'Đã đối chiếu',
  RECORDED: 'Đã ghi nhận',
  RECOUNT: 'Cần kiểm đếm lại',
  RELEASED: 'Đã phát hành',
  REPRINT_REQUIRED: 'Cần in lại',
  RETRYABLE: 'Có thể thử lại',
  REVIEW: 'Cần rà soát',
  Review: 'Cần rà soát',
  SELECTED: 'Đã chọn',
  SENT: 'Đã gửi',
  SERVICING: 'Đang phục vụ',
  SIMULATED: 'Đã mô phỏng',
  SPIKE: 'Tăng đột biến',
  UNDER_REVIEW: 'Đang rà soát',
  VALIDATED: 'Đã kiểm tra hợp lệ',
  VERIFIED: 'Đã xác minh',
  WARNING: 'Cảnh báo',
  Warning: 'Cảnh báo',
};

const ownerLabels: Record<string, string> = {
  '3PL Billing': 'Bộ phận tính phí 3PL',
  'Activity Projection': 'Dự phóng hoạt động',
  'Allocation Policy': 'Chính sách phân bổ',
  'Analytics Pipeline': 'Luồng xử lý phân tích',
  'Analytics Projection': 'Dự phóng phân tích',
  'Anomaly Worker': 'Tiến trình phát hiện bất thường',
  'Asset Registry': 'Sổ đăng ký tài sản',
  'Assist Device Gateway': 'Cổng thiết bị hỗ trợ',
  'Audit Service': 'Dịch vụ kiểm toán',
  'Automation Gateway': 'Cổng tự động hóa',
  'Billing Projection': 'Dự phóng tính phí',
  'Carrier Adapter': 'Bộ kết nối đơn vị vận chuyển',
  'Classification Worker': 'Tiến trình phân loại',
  'Cold Chain Monitor': 'Giám sát chuỗi lạnh',
  'Compliance Officer': 'Phụ trách tuân thủ',
  'Compliance Rules': 'Quy tắc tuân thủ',
  'Evidence Service': 'Dịch vụ bằng chứng',
  'Exception Engine': 'Bộ máy ngoại lệ',
  'Finance Adapter': 'Bộ kết nối tài chính',
  'Forecast Adapter': 'Bộ kết nối dự báo',
  'Import Worker': 'Tiến trình nhập dữ liệu',
  'Integration Control': 'Điều phối tích hợp',
  'Integration Worker': 'Tiến trình tích hợp',
  'Integrity Monitor': 'Giám sát toàn vẹn',
  'Inventory Owner Service': 'Dịch vụ chủ sở hữu tồn kho',
  'Inventory Posting Engine': 'Bộ máy ghi sổ tồn kho',
  'IoT Gateway': 'Cổng IoT',
  'Kitting Engine': 'Bộ máy lắp bộ',
  'Master Data Admin': 'Quản trị dữ liệu nền',
  'Notification Worker': 'Tiến trình thông báo',
  'Operations': 'Vận hành',
  'Optimization Engine': 'Bộ máy tối ưu',
  'Outbox Worker': 'Tiến trình hộp thư đi',
  'Planning Engine': 'Bộ máy lập kế hoạch',
  'Platform Admin': 'Quản trị nền tảng',
  'Policy Engine': 'Bộ máy chính sách',
  'Policy Registry': 'Sổ đăng ký chính sách',
  'Privacy Officer': 'Phụ trách quyền riêng tư',
  'Product Operations': 'Vận hành sản phẩm',
  'Production Support': 'Hỗ trợ hệ thống thật',
  'Promise Engine': 'Bộ máy cam kết đáp ứng',
  'Reconciliation Worker': 'Tiến trình đối chiếu',
  'Returns Work Center': 'Trung tâm xử lý hàng trả',
  'Risk Engine': 'Bộ máy rủi ro',
  'Routing Engine': 'Bộ máy định tuyến',
  'Safety Policy': 'Chính sách an toàn',
  'Search Projection': 'Dự phóng tìm kiếm',
  'Simulation Engine': 'Bộ máy mô phỏng',
  'Supplier Analytics': 'Phân tích nhà cung cấp',
  'System Admin': 'Quản trị hệ thống',
  'System Projection': 'Dự phóng hệ thống',
  'System Report': 'Báo cáo hệ thống',
  'Task Engine': 'Bộ máy nhiệm vụ',
  'VAS Work Center': 'Trung tâm dịch vụ gia tăng',
  'Warehouse Admin': 'Quản trị kho',
  'Warehouse Operator': 'Nhân viên vận hành kho',
};

const phraseReplacements: Array<[string, string]> = [
  ['Hoàn tất receiving', 'Hoàn tất tiếp nhận'],
  ['Putaway không có location phù hợp', 'Cất hàng không có vị trí phù hợp'],
  ['Outbound backlog', 'Tồn đọng xuất kho'],
  ['task', 'nhiệm vụ'],
  ['high priority', 'ưu tiên cao'],
  ['blocked', 'bị chặn'],
  ['Exact-first index', 'Chỉ mục ưu tiên khớp chính xác'],
  ['Product / Barcode / Document / Lot / Serial / Partner', 'Sản phẩm / Mã vạch / Chứng từ / Lô / Sê-ri / Đối tác'],
  ['received', 'đã nhận'],
  ['pending', 'đang chờ'],
  ['short exception opened', 'đã mở ngoại lệ thiếu hàng'],
  ['Serial tracked', 'theo dõi sê-ri'],
  ['max ', 'tối đa '],
  ['delivery accuracy', 'độ chính xác giao hàng'],
  ['dock-to-stock target', 'mục tiêu từ cửa kho đến sẵn sàng tồn'],
  ['capacity', 'sức chứa'],
  ['Zone ', 'Khu '],
  ['Aisle ', 'Dãy '],
  ['Rack ', 'Kệ '],
  ['Level ', 'Tầng '],
  ['Bin ', 'Ô '],
  ['Dock ', 'Cửa kho '],
  ['extended shift', 'ca mở rộng'],
  ['emergency override none', 'không có ghi đè khẩn cấp'],
  ['reserve ', 'giữ '],
  ['Wave ', 'Đợt '],
  [' lines', ' dòng'],
  ['dispatch', 'xác nhận giao'],
  ['receiver evidence attached', 'đã đính kèm bằng chứng người nhận'],
  ['OnHand', 'Tồn thực tế'],
  ['Available', 'Khả dụng'],
  ['freeze cycle count', 'đóng băng kiểm kê chu kỳ'],
  ['Ledger = Balance', 'Sổ cái = Số dư'],
  ['unexplained difference', 'chênh lệch chưa giải thích'],
  ['projection current', 'dự phóng hiện hành'],
  ['Pick face', 'Vị trí lấy hàng'],
  ['Attempt ', 'Lần '],
  ['accepted', 'đã chấp nhận'],
  ['system ', 'hệ thống '],
  ['counted ', 'đã đếm '],
  ['blind count', 'kiểm kê mù'],
  ['Variance ', 'Chênh lệch '],
  ['Pallet receiving', 'Pallet tiếp nhận'],
  ['carton ', 'thùng '],
  ['reprint audit', 'kiểm toán in lại'],
  ['Trailer ', 'Rơ-moóc '],
  ['chờ dock', 'chờ cửa kho'],
  ['không putaway', 'không cất hàng'],
  ['Snapshot ', 'Ảnh chụp '],
  [' lot ', ' lô '],
  ['Ledger-derived balance', 'Số dư suy ra từ sổ cái'],
  ['operational balance', 'số dư vận hành'],
  ['Stock turnover', 'Vòng quay tồn kho'],
  ['Days on Hand', 'Số ngày tồn kho'],
  ['grain ', 'kỳ tổng hợp '],
  ['semantic warehouse', 'kho dữ liệu ngữ nghĩa'],
  ['Warehouse Manager', 'Quản lý kho'],
  ['requires warehouse scope', 'yêu cầu phạm vi kho'],
  ['SoD enforced', 'đã áp dụng phân tách nhiệm vụ'],
  ['next ', 'tiếp theo '],
  ['Cold-chain', 'Chuỗi lạnh'],
  ['version ', 'phiên bản '],
  ['checksum verified', 'đã xác minh mã kiểm tra'],
  ['Level ', 'Mức '],
  ['metric units', 'đơn vị hệ mét'],
  ['templates', 'mẫu biểu'],
  ['audit required', 'yêu cầu kiểm toán'],
  ['callback', 'phản hồi'],
  ['preview ready', 'bản xem trước sẵn sàng'],
  ['cutoff', 'giờ chốt'],
  ['movement totals exported', 'đã xuất tổng biến động'],
  ['finance ack matched', 'xác nhận tài chính đã khớp'],
  ['Source ', 'Nguồn '],
  ['target ack', 'xác nhận đích'],
  ['retry', 'thử lại'],
  ['version conflict', 'xung đột phiên bản'],
  ['evidence/context preserved', 'giữ nguyên bằng chứng/ngữ cảnh'],
  ['Full backup + restore verification', 'Sao lưu đầy đủ + xác minh khôi phục'],
  ['mismatch', 'không khớp'],
  ['Outbox backlog', 'Tồn đọng hộp thư đi'],
  ['messages', 'thông điệp'],
  ['scan p95', 'quét p95'],
  ['no business KPI use', 'không dùng làm KPI nghiệp vụ'],
  ['integrations stop', 'dừng tích hợp'],
  ['evidence/data exit', 'bằng chứng/thoát dữ liệu'],
  ['Posted receipt error', 'Lỗi phiếu nhập đã ghi sổ'],
  ['corrected transaction plan', 'kế hoạch giao dịch hiệu chỉnh'],
  ['Trace document', 'Truy chứng từ'],
  ['without direct DB write', 'không ghi trực tiếp cơ sở dữ liệu'],
  ['storage/handling draft', 'bản nháp lưu trữ/xử lý'],
  ['maintenance due', 'đến hạn bảo trì'],
  ['components reserved', 'đã giữ các thành phần'],
  ['Relabel', 'Dán nhãn lại'],
  ['cube utilization', 'mức sử dụng thể tích'],
  ['no auto-pack', 'không tự đóng gói'],
  ['load sequence groups', 'nhóm thứ tự xếp hàng'],
  ['refurbish / RTV / scrap options', 'các lựa chọn tân trang / trả nhà cung cấp / tiêu hủy'],
  ['Heavy-lift', 'Nâng tải nặng'],
  ['qualified equipment/operator', 'thiết bị/người vận hành đủ điều kiện'],
  ['job', 'công việc'],
  ['not inventory truth', 'không phải sự thật tồn kho'],
  ['deduped', 'đã loại trùng'],
  ['device', 'thiết bị'],
  ['Voice prompt + pick-to-light', 'Nhắc bằng giọng nói + đèn hướng dẫn lấy hàng'],
  ['task semantics unchanged', 'ngữ nghĩa nhiệm vụ không đổi'],
  ['restricted zone', 'khu hạn chế'],
  ['segregation required', 'yêu cầu phân tách'],
  ['evidence captured', 'đã ghi nhận bằng chứng'],
  ['disposition pending', 'chờ quyết định xử lý'],
  ['actual', 'thực tế'],
  ['dual-UOM tolerance valid', 'dung sai hai đơn vị tính hợp lệ'],
  ['physical custody WMS', 'WMS giữ quyền quản lý vật lý'],
  ['explicit reclassification only', 'chỉ phân loại lại tường minh'],
  ['rating', 'tính giá'],
  ['reconciliation evidence ready', 'bằng chứng đối chiếu sẵn sàng'],
  ['promise ', 'cam kết '],
  ['surplus', 'dư'],
  ['shortage', 'thiếu'],
  ['transfer economics positive', 'hiệu quả điều chuyển tích cực'],
  ['execution requires transfer', 'thực thi yêu cầu điều chuyển'],
  ['availability/SLA/capacity score', 'điểm khả dụng/SLA/sức chứa'],
  ['Demand plan', 'Kế hoạch nhu cầu'],
  ['source ERP Planning', 'nguồn ERP Lập kế hoạch'],
  ['Safety ', 'Tồn an toàn '],
  ['velocity high', 'tốc độ luân chuyển cao'],
  ['variability low', 'biến động thấp'],
  ['expiry/capacity constraints satisfied', 'đạt ràng buộc hạn dùng/sức chứa'],
  ['Scenario ', 'Kịch bản '],
  ['projected shortage', 'thiếu hụt dự phóng'],
  ['Bias ', 'Độ lệch '],
  ['segment ', 'phân khúc '],
  ['no eligible source', 'không có nguồn đủ điều kiện'],
  ['escalation pending', 'chờ leo thang xử lý'],
  ['projected below reorder threshold', 'dự phóng dưới ngưỡng đặt hàng lại'],
  ['Risk ', 'Rủi ro '],
  ['stockout', 'hết hàng'],
  ['supplier variability elevated', 'biến động nhà cung cấp tăng'],
  ['Median ', 'Trung vị '],
  ['reliability', 'độ tin cậy'],
  ['Expedite ', 'Thúc đẩy '],
  ['service-risk reduction', 'giảm rủi ro dịch vụ'],
  ['Demand ', 'Nhu cầu '],
  ['vs baseline', 'so với đường cơ sở'],
  ['classification ', 'phân loại '],
  ['service class + fairness weights', 'hạng dịch vụ + trọng số công bằng'],
  ['deterministic proposal', 'đề xuất xác định'],
  ['fulfillment SLA', 'SLA đáp ứng'],
  ['target fill rate', 'mục tiêu tỷ lệ đáp ứng'],
  ['capacity -', 'sức chứa -'],
  ['no production mutation', 'không thay đổi hệ thống thật'],
  ['human approval required', 'yêu cầu phê duyệt của con người'],
];

export const mockTypeLabel = (value?: string | null) =>
  value ? (typeLabels[value] ?? value) : '—';

export const mockStatusLabel = (value?: string | null) =>
  value ? (statusLabels[value] ?? value) : '—';

export const mockOwnerLabel = (value?: string | null) =>
  value ? (ownerLabels[value] ?? value) : '—';

export const mockDisplayText = (value?: string | null) => {
  if (!value) return '—';
  const exact = typeLabels[value] ?? statusLabels[value] ?? ownerLabels[value];
  if (exact) return exact;
  return phraseReplacements.reduce(
    (current, [source, target]) => current.split(source).join(target),
    value,
  );
};
